import {useState,useEffect} from 'react';
import {newsAPI} from '../services/api';
import {toast} from 'react-toastify';
export const articlePayload = values => Object.fromEntries(['title','summary','content','category','image','tags'].filter(key=>values[key]!==undefined).map(key=>[key,values[key]]));
export default function ArticleFields({values,setValues,disabled=false,uploadImage,onUploading=()=>{}}){
 const [categories,setCategories]=useState([]),[error,setError]=useState(''),[uploading,setUploading]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{let live=true;newsAPI.getCategories().then(({data})=>{if(!live)return;setCategories(data.data);setError('');setValues(old=>({...old,category:old.category||data.data[0]?.slug||''}));}).catch(()=>{if(live)setError('Не удалось загрузить категории');});return()=>{live=false;};},[retry]);
 const change=e=>setValues(old=>({...old,[e.target.name]:e.target.value}));
 async function upload(e){const file=e.target.files[0];if(!file)return;if(file.size>5*1024*1024){toast.error('Изображение должно быть не больше 5 МБ');return;}setUploading(true);onUploading(true);try{const data=new FormData();data.append('image',file);const response=await uploadImage(data);setValues(old=>({...old,image:response.data.data.path}));toast.success('Изображение загружено');}catch(error){toast.error(error.response?.data?.message||'Не удалось загрузить изображение');}finally{setUploading(false);onUploading(false);e.target.value='';}}
 const input='w-full mt-2 border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:border-primary-600';
 return <fieldset disabled={disabled} className="space-y-5"><label className="block font-medium">Название<input className={input} name="title" value={values.title||''} onChange={change} required maxLength={200}/></label><label className="block font-medium">Краткое описание<textarea className={input} name="summary" value={values.summary||''} onChange={change} rows={3} maxLength={500}/></label><label className="block font-medium">Текст публикации<textarea className={input} name="content" value={values.content||''} onChange={change} required rows={12} maxLength={100000}/><span className="block text-sm text-gray-500 font-normal mt-1">Поддерживается безопасный HTML: абзацы, списки, ссылки и заголовки.</span></label><label className="block font-medium">Категория<select className={input} name="category" value={values.category||''} onChange={change} required><option value="" disabled>Выберите категорию</option>{categories.map(c=><option key={c.id} value={c.slug}>{c.name}</option>)}</select></label>{error&&<p role="alert" className="text-red-600">{error} <button type="button" className="underline" onClick={()=>setRetry(r=>r+1)}>Повторить</button></p>}<label className="block font-medium">Изображение<input className={input} name="image" value={values.image||''} onChange={change} maxLength={2000} placeholder="https://example.org/image.jpg или загрузите файл"/></label>{uploadImage&&<label className="inline-flex items-center gap-3 px-4 py-2 bg-gray-100 rounded-lg cursor-pointer"><span>{uploading?'Загрузка...':'Загрузить изображение'}</span><input type="file" accept="image/jpeg,image/png,image/gif,image/webp" disabled={disabled||uploading} onChange={upload} className="hidden"/></label>}{values.image&&<img src={values.image} alt="Предпросмотр обложки" className="max-h-56 rounded-xl max-w-full object-contain"/>}</fieldset>;
}
