import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useAuth} from '../context/AuthContext';
import {myPostsAPI} from '../services/api';
import {statusLabel} from '../utils/labels';
import Loading from '../components/Loading';
export default function MyPublications(){
 const {isAuthenticated,loading:authLoading}=useAuth();
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[page,setPage]=useState(1),[pages,setPages]=useState(1),[status,setStatus]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{if(!isAuthenticated)return;let live=true;setLoading(true);myPostsAPI.list({page,limit:12,status}).then(({data})=>{if(live){setItems(data.data);setPages(data.totalPages);setError('');}}).catch(e=>{if(live)setError(e.response?.data?.message||'Не удалось загрузить публикации');}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[isAuthenticated,page,status,retry]);
 if(authLoading)return <Loading/>;
 if(!isAuthenticated)return <div className="max-w-xl mx-auto p-12 text-center"><h1 className="text-2xl font-bold mb-4">Войдите, чтобы открыть свои публикации</h1><Link to="/login" className="text-primary-700">Войти</Link></div>;
 return <div className="max-w-5xl mx-auto px-4 py-8"><div className="flex flex-wrap gap-4 justify-between items-center mb-6"><div><p className="text-sm text-gray-500">Личный кабинет автора</p><h1 className="text-3xl font-bold">Мои публикации</h1></div><Link to="/my/posts/create" className="px-5 py-3 bg-primary-600 text-white rounded-lg">Предложить новость</Link></div><p className="text-gray-500 mb-6">Материалы появляются на сайте после проверки редакцией. Изменения опубликованных новостей проходят повторную проверку.</p><label className="block mb-6">Статус <select className="ml-3 border rounded-lg px-3 py-2" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Все публикации</option>{['draft','PENDING_REVIEW','published','rejected'].map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></label>{error?<div role="alert" className="bg-red-50 p-6 rounded-xl">{error} <button className="underline" onClick={()=>setRetry(r=>r+1)}>Повторить</button></div>:loading?<Loading/>:items.length===0?<div className="bg-white p-12 text-center border rounded-xl text-gray-500">Пока нет публикаций с этим статусом.</div>:<div className="space-y-4">{items.map(item=><article key={item.id} className="bg-white border border-gray-200 rounded-xl p-6"><div className="flex justify-between items-start gap-4"><div className="min-w-0"><span className={'inline-block text-xs rounded-full px-3 py-1 mb-2 '+(item.status==='published'?'bg-green-50 text-green-700':item.status==='rejected'?'bg-red-50 text-red-700':'bg-primary-50 text-primary-700')}>{statusLabel(item.status)}</span><h2 className="font-bold text-xl break-words">{item.title}</h2><p className="text-gray-500 text-sm mt-2">{item.categoryName} · {new Date(item.updatedAt).toLocaleDateString('ru-RU')}</p></div><Link to={'/my/posts/'+item.id} className="text-primary-700 whitespace-nowrap">{item.status==='PENDING_REVIEW'?'Открыть':'Редактировать'}</Link></div>{item.rejectionReason&&<p className="bg-red-50 rounded-lg p-3 mt-4 text-sm break-words">Комментарий редакции: {item.rejectionReason}</p>}{item.hasPublishedVersion&&item.status!=='published'&&<p className="text-sm text-gray-500 mt-3">На сайте доступна предыдущая одобренная версия.</p>}</article>)}</div>}<div className="flex justify-center gap-4 mt-8"><button disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)}>Назад</button><span>Страница {page} из {Math.max(1,pages)}</span><button disabled={page>=pages||loading} onClick={()=>setPage(p=>p+1)}>Далее</button></div></div>;
}
