import {useState,useEffect} from 'react';
import {Link,useParams,useNavigate} from 'react-router-dom';
import {toast} from 'react-toastify';
import {useAuth} from '../context/AuthContext';
import {myPostsAPI} from '../services/api';
import {statusLabel} from '../utils/labels';
import ArticleFields,{articlePayload} from '../components/ArticleFields';
import Loading from '../components/Loading';
export default function SubmitArticle(){
 const {id}=useParams(),navigate=useNavigate(),{isAuthenticated,loading:authLoading}=useAuth();
 const [values,setValues]=useState({title:'',summary:'',content:'',category:'',image:''}),[article,setArticle]=useState(null),[loading,setLoading]=useState(Boolean(id)),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!id){setArticle(null);setValues({title:'',summary:'',content:'',category:'technology',image:''});setLoading(false);setError('');return;}if(!isAuthenticated)return;let live=true;setLoading(true);myPostsAPI.get(id).then(({data})=>{if(live){setArticle(data.data);setValues(articlePayload(data.data));setError('');}}).catch(e=>{if(live)setError(e.response?.data?.message||'Не удалось загрузить публикацию');}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[id,isAuthenticated]);
 async function save(e){e.preventDefault();const intent=e.nativeEvent.submitter?.value||'submit';setBusy(true);try{if(id){await myPostsAPI.update(id,articlePayload(values));if(intent==='submit')await myPostsAPI.submit(id);}else await myPostsAPI.create({...articlePayload(values),intent});toast.success(intent==='submit'?'Материал отправлен на проверку':'Черновик сохранён');navigate('/my/posts');}catch(e){toast.error(e.response?.data?.message||'Не удалось сохранить публикацию');}finally{setBusy(false);}}
 if(authLoading||loading&&isAuthenticated)return <Loading/>;
 if(!isAuthenticated)return <div className="max-w-xl mx-auto p-12 text-center"><h1 className="text-2xl font-bold mb-4">Войдите, чтобы предложить новость</h1><Link to="/login" className="text-primary-700">Войти</Link><p className="mt-4">Нет аккаунта? <Link to="/register" className="text-primary-700">Регистрация</Link></p></div>;
 const pending=article?.status==='PENDING_REVIEW';
 return <div className="max-w-4xl mx-auto px-4 py-8"><Link to="/my/posts" className="text-primary-700">← Мои публикации</Link><h1 className="text-3xl font-bold mt-4 mb-3">{id?'Моя публикация':'Предложить новость'}</h1><p className="text-gray-500 mb-6">Авторство сохраняется за вами. Публикация и изменения текста проходят проверку редакцией.</p>{error?<div role="alert" className="bg-red-50 p-6 rounded-xl">{error}</div>:<><div className="mb-6 space-y-2">{article&&<p>Статус: <strong>{statusLabel(article.status)}</strong></p>}{pending&&<p className="bg-primary-50 p-4 rounded-xl">Материал на проверке. Изменения доступны после решения редакции.</p>}{article?.hasPublishedVersion&&<p className="text-sm text-gray-500">Одобренная версия остаётся на сайте. Сохранение новой версии не изменит публичный текст.</p>}{article?.rejectionReason&&<p className="bg-red-50 p-4 rounded-xl">Комментарий редакции: {article.rejectionReason}</p>}</div><form onSubmit={save} className="bg-white border border-gray-200 p-5 md:p-8 rounded-xl"><ArticleFields values={values} setValues={setValues} disabled={pending||busy} uploadImage={myPostsAPI.uploadImage} onUploading={setUploading}/>{!pending&&<div className="flex flex-wrap gap-3 mt-8"><button type="submit" value="submit" disabled={busy||uploading} className="bg-primary-600 text-white px-5 py-3 rounded-lg">{busy?'Сохранение...':'Отправить на проверку'}</button><button type="submit" value="draft" disabled={busy||uploading} className="border border-gray-300 px-5 py-3 rounded-lg">Сохранить черновик</button></div>}</form>{article?.history?.length>0&&<section className="bg-white border rounded-xl p-6 mt-6"><h2 className="text-lg font-semibold mb-4">История версий</h2><ul className="space-y-3">{article.history.map(item=><li key={item.id} className="text-sm">Версия {item.version}: {statusLabel(item.status)}{item.rejectionReason&&<p className="text-gray-500">{item.rejectionReason}</p>}</li>)}</ul></section>}</>}</div>;
}
