import {useEffect,useState} from 'react';
import {useParams,Link,useNavigate} from 'react-router-dom';
import {toast} from 'react-toastify';
import {submissionsAPI,adminAPI} from '../../services/api';
import {statusLabel,categoryLabel} from '../../utils/labels';
import ArticleFields,{articlePayload} from '../../components/ArticleFields';
import Loading from '../../components/Loading';
export default function SubmissionReview(){
 const {id}=useParams(),navigate=useNavigate();
 const [item,setItem]=useState(null),[values,setValues]=useState({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState('');
 useEffect(()=>{let live=true;setLoading(true);submissionsAPI.get(id).then(({data})=>{if(live){setItem(data.data);setValues(articlePayload(data.data));setReason(data.data.rejectionReason||'');setError('');}}).catch(e=>{if(live)setError(e.response?.data?.message||'Не удалось загрузить материал');}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[id]);
 async function save(e){e.preventDefault();const approve=e.nativeEvent.submitter?.value==='approve';setBusy(true);try{if(approve){await submissionsAPI.decide(id,'approve',undefined,articlePayload(values));toast.success('Материал опубликован. Автор сохранён.');navigate('/admin/submissions');}else{const response=await submissionsAPI.update(id,articlePayload(values));setItem(response.data.data);toast.success('Редакционные правки сохранены');}}catch(e){toast.error(e.response?.data?.message||'Не удалось сохранить решение');}finally{setBusy(false);}}
 async function reject(){setBusy(true);try{await submissionsAPI.decide(id,'reject',reason);toast.success('Материал отклонён');navigate('/admin/submissions');}catch(e){toast.error(e.response?.data?.message||'Не удалось отклонить материал');}finally{setBusy(false);}}
 if(loading)return <Loading/>;
 if(error)return <div role="alert" className="bg-red-50 p-6 rounded-xl">{error}<Link to="/admin/submissions" className="block underline mt-4">Вернуться к очереди</Link></div>;
 const editable=item.status==='PENDING_REVIEW'&&item.isCurrentVersion;
 const original=item.originalSubmission;
 return <div className="max-w-5xl mx-auto"><Link to="/admin/submissions" className="text-primary-700">← Новости на проверке</Link><h1 className="text-3xl font-bold mt-4 mb-4">Проверка публикации</h1><div className="bg-primary-50 border border-primary-100 rounded-xl p-5 mb-6"><strong>Автор: {item.author.name}</strong><p className="text-sm mt-1">Версия {item.version} · {statusLabel(item.status)}. Редактирование и публикация не меняют автора.</p>{item.hasPublishedVersion&&<p className="text-sm mt-2">До одобрения новой версии на сайте остаётся предыдущий текст.</p>}{item.reviewerName&&<p className="text-sm mt-2">Проверил: {item.reviewerName}</p>}{item.rejectionReason&&<p className="text-sm mt-2">Причина: {item.rejectionReason}</p>}</div>{original&&<details className="bg-white border rounded-xl p-5 mb-6" open><summary className="font-semibold cursor-pointer">Исходная отправка автора</summary><div className="mt-4 space-y-3"><h2 className="text-xl font-bold">{original.title}</h2><p className="text-sm text-gray-500">{original.categoryName||categoryLabel(original.category)}</p><p className="text-gray-600 whitespace-pre-wrap">{original.summary}</p>{original.image&&<img src={original.image} alt="Исходная обложка" className="max-h-56 rounded-lg"/>}<div className="prose max-w-none" dangerouslySetInnerHTML={{__html:original.content}}/></div></details>}<form onSubmit={save} className="bg-white border rounded-xl p-5 md:p-8"><h2 className="text-xl font-semibold mb-6">Редакционная версия</h2><ArticleFields values={values} setValues={setValues} disabled={busy||!editable} uploadImage={adminAPI.uploadImage} onUploading={setUploading}/>{editable&&<div className="mt-8 flex flex-wrap gap-3"><button type="submit" value="approve" disabled={busy||uploading} className="bg-primary-600 text-white rounded-lg px-5 py-3">Одобрить и опубликовать</button><button type="submit" value="save" disabled={busy||uploading} className="border border-gray-300 rounded-lg px-5 py-3">Сохранить правки</button></div>}</form>{editable&&<section className="bg-white border rounded-xl p-6 mt-6"><h2 className="font-semibold mb-3">Отклонить материал</h2><label className="block text-sm text-gray-500">Объяснение для автора (необязательно)<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} className="block w-full border rounded-lg p-3 mt-2" rows={3}/></label><button disabled={busy||uploading} onClick={reject} className="bg-red-50 text-red-700 px-5 py-3 rounded-lg mt-4">Отклонить</button></section>}</div>;
}
