import {useState,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {submissionsAPI} from '../../services/api';
import Loading from '../../components/Loading';
export default function SubmissionList(){
 const [items,setItems]=useState([]),[page,setPage]=useState(1),[pages,setPages]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let live=true;setLoading(true);submissionsAPI.list({status:'PENDING_REVIEW',page,limit:12}).then(({data})=>{if(live){setItems(data.data);setPages(data.totalPages);setError('');}}).catch(e=>{if(live)setError(e.response?.data?.message||'Не удалось загрузить очередь');}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[page,retry]);
 return <div><p className="text-sm text-gray-500 mb-2">Материалы авторов</p><h1 className="text-3xl font-bold mb-3">Новости на проверке</h1><p className="text-gray-500 mb-6">Проверьте исходный текст, внесите правки и примите решение. Авторство сохраняется за пользователем.</p>{error?<div role="alert" className="bg-red-50 p-6 rounded-xl">{error} <button className="underline" onClick={()=>setRetry(r=>r+1)}>Повторить</button></div>:loading?<Loading/>:items.length===0?<div className="bg-white border rounded-xl p-12 text-center text-gray-500">Все материалы рассмотрены. Новых отправок пока нет.</div>:<div className="space-y-4">{items.map(item=><article className="bg-white rounded-xl border p-6" key={item.id}><div className="flex flex-wrap gap-4 justify-between"><div className="min-w-0"><p className="text-primary-700 text-xs mb-2">{item.hasPublishedVersion?'Повторная проверка':'Новая публикация'} · Версия {item.version}</p><h2 className="text-xl font-bold break-words">{item.title}</h2><p className="text-gray-500 text-sm mt-2">Автор: {item.author.name} · {item.categoryName}</p><p className="text-gray-500 text-sm">Отправлено: {new Date(item.submittedAt).toLocaleString('ru-RU')}</p></div><Link to={'/admin/submissions/'+item.id} className="self-center px-4 py-2 bg-primary-600 rounded-lg text-white">Рассмотреть</Link></div><p className="text-gray-500 mt-4 line-clamp-2">{item.summary}</p></article>)}</div>}<div className="flex justify-center gap-4 mt-8"><button disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)}>Назад</button><span>Страница {page} из {Math.max(1,pages)}</span><button disabled={page>=pages||loading} onClick={()=>setPage(p=>p+1)}>Далее</button></div></div>;
}
